// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: pkg/proto/configuration/bb_browser/bb_browser.proto

package bb_browser

import (
	auth "github.com/buildbarn/bb-storage/pkg/proto/configuration/auth"
	blobstore "github.com/buildbarn/bb-storage/pkg/proto/configuration/blobstore"
	global "github.com/buildbarn/bb-storage/pkg/proto/configuration/global"
	http "github.com/buildbarn/bb-storage/pkg/proto/configuration/http"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplicationConfiguration struct {
	state                                  protoimpl.MessageState             `protogen:"open.v1"`
	Blobstore                              *blobstore.BlobstoreConfiguration  `protobuf:"bytes,1,opt,name=blobstore,proto3" json:"blobstore,omitempty"`
	MaximumMessageSizeBytes                int64                              `protobuf:"varint,2,opt,name=maximum_message_size_bytes,json=maximumMessageSizeBytes,proto3" json:"maximum_message_size_bytes,omitempty"`
	HttpServers                            []*http.ServerConfiguration        `protobuf:"bytes,10,rep,name=http_servers,json=httpServers,proto3" json:"http_servers,omitempty"`
	RoutePrefix                            string                             `protobuf:"bytes,7,opt,name=route_prefix,json=routePrefix,proto3" json:"route_prefix,omitempty"`
	Global                                 *global.Configuration              `protobuf:"bytes,4,opt,name=global,proto3" json:"global,omitempty"`
	BbClientdInstanceNamePrefix            string                             `protobuf:"bytes,5,opt,name=bb_clientd_instance_name_prefix,json=bbClientdInstanceNamePrefix,proto3" json:"bb_clientd_instance_name_prefix,omitempty"`
	InitialSizeClassCache                  *blobstore.BlobAccessConfiguration `protobuf:"bytes,6,opt,name=initial_size_class_cache,json=initialSizeClassCache,proto3" json:"initial_size_class_cache,omitempty"`
	FileSystemAccessCache                  *blobstore.BlobAccessConfiguration `protobuf:"bytes,9,opt,name=file_system_access_cache,json=fileSystemAccessCache,proto3" json:"file_system_access_cache,omitempty"`
	Authorizer                             *auth.AuthorizerConfiguration      `protobuf:"bytes,8,opt,name=authorizer,proto3" json:"authorizer,omitempty"`
	RequestMetadataLinksJmespathExpression string                             `protobuf:"bytes,11,opt,name=request_metadata_links_jmespath_expression,json=requestMetadataLinksJmespathExpression,proto3" json:"request_metadata_links_jmespath_expression,omitempty"`
	unknownFields                          protoimpl.UnknownFields
	sizeCache                              protoimpl.SizeCache
}

func (x *ApplicationConfiguration) Reset() {
	*x = ApplicationConfiguration{}
	mi := &file_pkg_proto_configuration_bb_browser_bb_browser_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationConfiguration) ProtoMessage() {}

func (x *ApplicationConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_configuration_bb_browser_bb_browser_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationConfiguration.ProtoReflect.Descriptor instead.
func (*ApplicationConfiguration) Descriptor() ([]byte, []int) {
	return file_pkg_proto_configuration_bb_browser_bb_browser_proto_rawDescGZIP(), []int{0}
}

func (x *ApplicationConfiguration) GetBlobstore() *blobstore.BlobstoreConfiguration {
	if x != nil {
		return x.Blobstore
	}
	return nil
}

func (x *ApplicationConfiguration) GetMaximumMessageSizeBytes() int64 {
	if x != nil {
		return x.MaximumMessageSizeBytes
	}
	return 0
}

func (x *ApplicationConfiguration) GetHttpServers() []*http.ServerConfiguration {
	if x != nil {
		return x.HttpServers
	}
	return nil
}

func (x *ApplicationConfiguration) GetRoutePrefix() string {
	if x != nil {
		return x.RoutePrefix
	}
	return ""
}

func (x *ApplicationConfiguration) GetGlobal() *global.Configuration {
	if x != nil {
		return x.Global
	}
	return nil
}

func (x *ApplicationConfiguration) GetBbClientdInstanceNamePrefix() string {
	if x != nil {
		return x.BbClientdInstanceNamePrefix
	}
	return ""
}

func (x *ApplicationConfiguration) GetInitialSizeClassCache() *blobstore.BlobAccessConfiguration {
	if x != nil {
		return x.InitialSizeClassCache
	}
	return nil
}

func (x *ApplicationConfiguration) GetFileSystemAccessCache() *blobstore.BlobAccessConfiguration {
	if x != nil {
		return x.FileSystemAccessCache
	}
	return nil
}

func (x *ApplicationConfiguration) GetAuthorizer() *auth.AuthorizerConfiguration {
	if x != nil {
		return x.Authorizer
	}
	return nil
}

func (x *ApplicationConfiguration) GetRequestMetadataLinksJmespathExpression() string {
	if x != nil {
		return x.RequestMetadataLinksJmespathExpression
	}
	return ""
}

var File_pkg_proto_configuration_bb_browser_bb_browser_proto protoreflect.FileDescriptor

const file_pkg_proto_configuration_bb_browser_bb_browser_proto_rawDesc = "" +
	"\n" +
	"3pkg/proto/configuration/bb_browser/bb_browser.proto\x12\"buildbarn.configuration.bb_browser\x1a'pkg/proto/configuration/auth/auth.proto\x1a1pkg/proto/configuration/blobstore/blobstore.proto\x1a+pkg/proto/configuration/global/global.proto\x1a'pkg/proto/configuration/http/http.proto\"\xd9\x06\n" +
	"\x18ApplicationConfiguration\x12W\n" +
	"\tblobstore\x18\x01 \x01(\v29.buildbarn.configuration.blobstore.BlobstoreConfigurationR\tblobstore\x12;\n" +
	"\x1amaximum_message_size_bytes\x18\x02 \x01(\x03R\x17maximumMessageSizeBytes\x12T\n" +
	"\fhttp_servers\x18\n" +
	" \x03(\v21.buildbarn.configuration.http.ServerConfigurationR\vhttpServers\x12!\n" +
	"\froute_prefix\x18\a \x01(\tR\vroutePrefix\x12E\n" +
	"\x06global\x18\x04 \x01(\v2-.buildbarn.configuration.global.ConfigurationR\x06global\x12D\n" +
	"\x1fbb_clientd_instance_name_prefix\x18\x05 \x01(\tR\x1bbbClientdInstanceNamePrefix\x12s\n" +
	"\x18initial_size_class_cache\x18\x06 \x01(\v2:.buildbarn.configuration.blobstore.BlobAccessConfigurationR\x15initialSizeClassCache\x12s\n" +
	"\x18file_system_access_cache\x18\t \x01(\v2:.buildbarn.configuration.blobstore.BlobAccessConfigurationR\x15fileSystemAccessCache\x12U\n" +
	"\n" +
	"authorizer\x18\b \x01(\v25.buildbarn.configuration.auth.AuthorizerConfigurationR\n" +
	"authorizer\x12Z\n" +
	"*request_metadata_links_jmespath_expression\x18\v \x01(\tR&requestMetadataLinksJmespathExpressionJ\x04\b\x03\x10\x04BDZBgithub.com/buildbarn/bb-browser/pkg/proto/configuration/bb_browserb\x06proto3"

var (
	file_pkg_proto_configuration_bb_browser_bb_browser_proto_rawDescOnce sync.Once
	file_pkg_proto_configuration_bb_browser_bb_browser_proto_rawDescData []byte
)

func file_pkg_proto_configuration_bb_browser_bb_browser_proto_rawDescGZIP() []byte {
	file_pkg_proto_configuration_bb_browser_bb_browser_proto_rawDescOnce.Do(func() {
		file_pkg_proto_configuration_bb_browser_bb_browser_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_configuration_bb_browser_bb_browser_proto_rawDesc), len(file_pkg_proto_configuration_bb_browser_bb_browser_proto_rawDesc)))
	})
	return file_pkg_proto_configuration_bb_browser_bb_browser_proto_rawDescData
}

var file_pkg_proto_configuration_bb_browser_bb_browser_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_proto_configuration_bb_browser_bb_browser_proto_goTypes = []any{
	(*ApplicationConfiguration)(nil),          // 0: buildbarn.configuration.bb_browser.ApplicationConfiguration
	(*blobstore.BlobstoreConfiguration)(nil),  // 1: buildbarn.configuration.blobstore.BlobstoreConfiguration
	(*http.ServerConfiguration)(nil),          // 2: buildbarn.configuration.http.ServerConfiguration
	(*global.Configuration)(nil),              // 3: buildbarn.configuration.global.Configuration
	(*blobstore.BlobAccessConfiguration)(nil), // 4: buildbarn.configuration.blobstore.BlobAccessConfiguration
	(*auth.AuthorizerConfiguration)(nil),      // 5: buildbarn.configuration.auth.AuthorizerConfiguration
}
var file_pkg_proto_configuration_bb_browser_bb_browser_proto_depIdxs = []int32{
	1, // 0: buildbarn.configuration.bb_browser.ApplicationConfiguration.blobstore:type_name -> buildbarn.configuration.blobstore.BlobstoreConfiguration
	2, // 1: buildbarn.configuration.bb_browser.ApplicationConfiguration.http_servers:type_name -> buildbarn.configuration.http.ServerConfiguration
	3, // 2: buildbarn.configuration.bb_browser.ApplicationConfiguration.global:type_name -> buildbarn.configuration.global.Configuration
	4, // 3: buildbarn.configuration.bb_browser.ApplicationConfiguration.initial_size_class_cache:type_name -> buildbarn.configuration.blobstore.BlobAccessConfiguration
	4, // 4: buildbarn.configuration.bb_browser.ApplicationConfiguration.file_system_access_cache:type_name -> buildbarn.configuration.blobstore.BlobAccessConfiguration
	5, // 5: buildbarn.configuration.bb_browser.ApplicationConfiguration.authorizer:type_name -> buildbarn.configuration.auth.AuthorizerConfiguration
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_proto_configuration_bb_browser_bb_browser_proto_init() }
func file_pkg_proto_configuration_bb_browser_bb_browser_proto_init() {
	if File_pkg_proto_configuration_bb_browser_bb_browser_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_configuration_bb_browser_bb_browser_proto_rawDesc), len(file_pkg_proto_configuration_bb_browser_bb_browser_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_configuration_bb_browser_bb_browser_proto_goTypes,
		DependencyIndexes: file_pkg_proto_configuration_bb_browser_bb_browser_proto_depIdxs,
		MessageInfos:      file_pkg_proto_configuration_bb_browser_bb_browser_proto_msgTypes,
	}.Build()
	File_pkg_proto_configuration_bb_browser_bb_browser_proto = out.File
	file_pkg_proto_configuration_bb_browser_bb_browser_proto_goTypes = nil
	file_pkg_proto_configuration_bb_browser_bb_browser_proto_depIdxs = nil
}
