// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: pkg/proto/query/query.proto

package query

import (
	v2 "github.com/bazelbuild/remote-apis/build/bazel/remote/execution/v2"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileSystemAccessProfileReference struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Digest             *v2.Digest             `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	PathHashesBaseHash uint64                 `protobuf:"varint,2,opt,name=path_hashes_base_hash,json=pathHashesBaseHash,proto3" json:"path_hashes_base_hash,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FileSystemAccessProfileReference) Reset() {
	*x = FileSystemAccessProfileReference{}
	mi := &file_pkg_proto_query_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileSystemAccessProfileReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileSystemAccessProfileReference) ProtoMessage() {}

func (x *FileSystemAccessProfileReference) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_query_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileSystemAccessProfileReference.ProtoReflect.Descriptor instead.
func (*FileSystemAccessProfileReference) Descriptor() ([]byte, []int) {
	return file_pkg_proto_query_query_proto_rawDescGZIP(), []int{0}
}

func (x *FileSystemAccessProfileReference) GetDigest() *v2.Digest {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *FileSystemAccessProfileReference) GetPathHashesBaseHash() uint64 {
	if x != nil {
		return x.PathHashesBaseHash
	}
	return 0
}

var File_pkg_proto_query_query_proto protoreflect.FileDescriptor

const file_pkg_proto_query_query_proto_rawDesc = "" +
	"\n" +
	"\x1bpkg/proto/query/query.proto\x12\x0fbuildbarn.query\x1a6build/bazel/remote/execution/v2/remote_execution.proto\"\x96\x01\n" +
	" FileSystemAccessProfileReference\x12?\n" +
	"\x06digest\x18\x01 \x01(\v2'.build.bazel.remote.execution.v2.DigestR\x06digest\x121\n" +
	"\x15path_hashes_base_hash\x18\x02 \x01(\x04R\x12pathHashesBaseHashB1Z/github.com/buildbarn/bb-browser/pkg/proto/queryb\x06proto3"

var (
	file_pkg_proto_query_query_proto_rawDescOnce sync.Once
	file_pkg_proto_query_query_proto_rawDescData []byte
)

func file_pkg_proto_query_query_proto_rawDescGZIP() []byte {
	file_pkg_proto_query_query_proto_rawDescOnce.Do(func() {
		file_pkg_proto_query_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_query_query_proto_rawDesc), len(file_pkg_proto_query_query_proto_rawDesc)))
	})
	return file_pkg_proto_query_query_proto_rawDescData
}

var file_pkg_proto_query_query_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_proto_query_query_proto_goTypes = []any{
	(*FileSystemAccessProfileReference)(nil), // 0: buildbarn.query.FileSystemAccessProfileReference
	(*v2.Digest)(nil),                        // 1: build.bazel.remote.execution.v2.Digest
}
var file_pkg_proto_query_query_proto_depIdxs = []int32{
	1, // 0: buildbarn.query.FileSystemAccessProfileReference.digest:type_name -> build.bazel.remote.execution.v2.Digest
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_query_query_proto_init() }
func file_pkg_proto_query_query_proto_init() {
	if File_pkg_proto_query_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_query_query_proto_rawDesc), len(file_pkg_proto_query_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_query_query_proto_goTypes,
		DependencyIndexes: file_pkg_proto_query_query_proto_depIdxs,
		MessageInfos:      file_pkg_proto_query_query_proto_msgTypes,
	}.Build()
	File_pkg_proto_query_query_proto = out.File
	file_pkg_proto_query_query_proto_goTypes = nil
	file_pkg_proto_query_query_proto_depIdxs = nil
}
