name: CI
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  gofmt:
    runs-on: ubuntu-latest
    container: docker://golang:1.13
    steps:
    - uses: actions/checkout@v1
    - name: run gofmt
      run: test -z "$(gofmt -d . | tee /dev/stderr)"
  gazelle:
    runs-on: ubuntu-latest
    container: docker://l.gcr.io/google/bazel:2.1.0
    steps:
    - uses: actions/checkout@v1
    - name: run gazelle
      run: bazel run :gazelle && git diff --exit-code HEAD --
  build:
    runs-on: ubuntu-latest
    container: docker://l.gcr.io/google/bazel:2.1.0
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: bazel build //...
